name: share_pro
description: "Flutter plugin for share data to another app"
version: 1.0.1
homepage: "https://navaghandabhi.github.io/navaghan/"

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.navaghan.share_pro
        pluginClass: SharerPlugin
      ios:
        pluginClass: SharerPlugin
