name: share_pro
description: A Flutter plugin that enables sharing text content to other apps on Android and iOS platforms.
version: 1.0.4
homepage: https://navaghandabhi.github.io/navaghan/
repository: https://github.com/DabhiNavaghan/share_pro

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.navaghan.share_pro
        pluginClass: SharerPlugin
      ios:
        pluginClass: SharerPlugin
